// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNP4jTF8PKUck3XHfvLTqyv47otmDb-A',
    appId: '1:706198488670:web:d5abdc2cfdc63bc07e96cf',
    messagingSenderId: '706198488670',
    projectId: 'smart-aqua-health',
    authDomain: 'smart-aqua-health.firebaseapp.com',
    storageBucket: 'smart-aqua-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKGFPkg8wIlJWeHQXIW2kG2NkxU-0ALw',
    appId: '1:706198488670:android:ed0a92aac33f71687e96cf',
    messagingSenderId: '706198488670',
    projectId: 'smart-aqua-health',
    storageBucket: 'smart-aqua-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKH_gCru-8t-ltda4WRNyviVJ9O1S3MS8',
    appId: '1:706198488670:ios:bf364be9a303e2497e96cf',
    messagingSenderId: '706198488670',
    projectId: 'smart-aqua-health',
    storageBucket: 'smart-aqua-health.firebasestorage.app',
    iosBundleId: 'com.example.smartAqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKH_gCru-8t-ltda4WRNyviVJ9O1S3MS8',
    appId: '1:706198488670:ios:bf364be9a303e2497e96cf',
    messagingSenderId: '706198488670',
    projectId: 'smart-aqua-health',
    storageBucket: 'smart-aqua-health.firebasestorage.app',
    iosBundleId: 'com.example.smartAqua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNP4jTF8PKUck3XHfvLTqyv47otmDb-A',
    appId: '1:706198488670:web:c93865426b88efcb7e96cf',
    messagingSenderId: '706198488670',
    projectId: 'smart-aqua-health',
    authDomain: 'smart-aqua-health.firebaseapp.com',
    storageBucket: 'smart-aqua-health.firebasestorage.app',
  );
}
